#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

run:
  concurrency: 4
  deadline: 3m
  issues-exit-code: 1
  tests: true
  build-tags: [""]
  skip-dirs:  [""]

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,io/ioutil:^Read.*
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
  golint:
    min-confidence: 0.6
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/trustbloc/sidetree-core-go
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    # default locale is a neutral variety of English.
    locale:
    ignore-words: []
  lll:
    line-length: 120
    tab-width: 1
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 0
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - opinionated
    disabled-checks:
      - unnamedResult
  funlen:
    lines: 60
    statements: 40
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-case-traling-whitespace: true
    allow-cuddle-declarations: false
  godot:
    check-all: false

linters:
  enable-all: true
  disable:
    - testpackage
    - maligned
    - prealloc
    - goerr113 # TODO enable
    - gochecknoglobals # TODO enable
    - wsl # TODO enable
    - lll # TODO enable
    - gocritic # TODO enable
    - noctx # TODO enable

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gomnd
        - gosec # TODO enable
        - ineffassign # TODO enable        
        - errcheck # TODO enable
        - nakedret # TODO enable
        - staticcheck # TODO enable
    - path: jsoncanonicalizer
      linters:
        - golint
        - funlen
        - gomnd
        - gosec
        - errcheck
        - gocyclo
        - gocognit
        - whitespace
        - nlreturn
        - godot
        - nestif
        - gofumpt
  exclude:
    # Allow package logger variables (for now)
    - \`logger\` is a global variable
    -  Line contains TODO/BUG/FIXME
    # Add comments for package
    -  at least one file in a package should have a package comment
    # Allow magic number 1
    - Magic number[:] 1[^\d]
